"""Download the site's fonts from Google Fonts once and self-host them.

Usage:  py -3.12 -I tools/fonts.py <repo_root>

Writes assets/fonts/*.woff2 and assets/css/fonts.css, so the site never depends on
fonts.googleapis.com at view time (blocked networks, privacy extensions, offline copies).
All three families are under the SIL Open Font License.
"""
import os
import re
import sys
import urllib.request

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
CSS_URL = ("https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..600;1,6..96,400..600"
           "&family=Inter:wght@400..500&family=Noto+Serif+Devanagari:wght@400&display=swap")
# Subsets kept per family; anything else (cyrillic, vietnamese…) is never used by the site.
KEEP = {"Bodoni Moda": {"latin", "latin-ext"}, "Inter": {"latin", "latin-ext"}, "Noto Serif Devanagari": {"devanagari"}}


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    root = sys.argv[1]
    font_dir = os.path.join(root, "assets", "fonts")
    os.makedirs(font_dir, exist_ok=True)
    css = get(CSS_URL).decode("utf-8")
    out = ["/* Self-hosted fonts (SIL Open Font License), generated by tools/fonts.py. */"]
    for subset, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        if subset not in KEEP.get(family, set()):
            continue
        style = re.search(r"font-style: (\w+)", block).group(1)
        weight = re.search(r"font-weight: ([\d ]+);", block).group(1)
        url = re.search(r"src: url\((https://[^)]+\.woff2)\)", block).group(1)
        urange = re.search(r"unicode-range: ([^;]+);", block).group(1)
        name = f"{family.lower().replace(' ', '-')}-{style}-{subset}.woff2"
        with open(os.path.join(font_dir, name), "wb") as f:
            f.write(get(url))
        out.append(f"@font-face {{\n  font-family: '{family}';\n  font-style: {style};\n  font-weight: {weight};\n"
                   f"  font-display: swap;\n  src: url(../fonts/{name}) format('woff2');\n  unicode-range: {urange};\n}}")
        print(f"{name}  ({os.path.getsize(os.path.join(font_dir, name)) // 1024} KB)")
    with open(os.path.join(root, "assets", "css", "fonts.css"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
